[package]
name = "mermaid"
version = "0.1.0"
edition = "2021"
description = "Experimental Linear Algebra"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
